name: Release
on: [push, workflow_dispatch]
env:
  version: '1.20.1'
  branch: master
jobs:
  paperclip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 'latest'
      - name: Configure Git User Details
        run: |
            git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
            echo "workflow=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: applyPatches and build
        run: |
            chmod 777 gradlew
            ./gradlew clean --stacktrace
            ./gradlew applyPatches --stacktrace
            ./gradlew createReobfPaperclipJar --stacktrace
      - name: Release Paperclip (latest)
        if: github.ref_name == env.branch
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build #${{ env.workflow }}"
          automatic_release_tag: latest-${{ env.version }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/atlanta-paperclip-*-reobf.jar
          prerelease: false
      - name: Release Paperclip (History)
        if: github.ref_name == env.branch
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build #${{ env.workflow }}"
          automatic_release_tag: build-${{ env.workflow }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/atlanta-paperclip-*-reobf.jar
          prerelease: false
